name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |       
        echo "${{ secrets.DOCKERPW }}" | docker login -u "spbravo" --password-stdin
        docker image build -t spbravo/gitops:goSlack1.1 .
        docker push spbravo/gitops:goSlack1.1
